PhanMemVeSo/PhanMemVeSo/Areas/Admin/Controllers/ADHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhanMemVeSo.Areas.Admin.Controllers
{
    public class ADHomeController : Controller
    {
        // GET: Admin/ADHome
        public ActionResult Index()
        {
            return View();
        }
    }
}

PhanMemVeSo/PhanMemVeSo/Areas/Admin/Controllers/DaiLysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.EFModels;

namespace PhanMemVeSo.Areas.Admin.Controllers
{
    public class DaiLysController : Controller
    {
        private PhanPhoiVeSoEntities db = new PhanPhoiVeSoEntities();

        // GET: Admin/DaiLys
        public ActionResult Index()
        {
            return View(db.DaiLies.ToList());
        }

        // GET: Admin/DaiLys/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DaiLy daiLy = db.DaiLies.Find(id);
            if (daiLy == null)
            {
                return HttpNotFound();
            }
            return View(daiLy);
        }

        // GET: Admin/DaiLys/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/DaiLys/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DaiLyId,TenDaiLy")] DaiLy daiLy)
        {
            if (ModelState.IsValid)
            {
                db.DaiLies.Add(daiLy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(daiLy);
        }

        // GET: Admin/DaiLys/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DaiLy daiLy = db.DaiLies.Find(id);
            if (daiLy == null)
            {
                return HttpNotFound();
            }
            return View(daiLy);
        }

        // POST: Admin/DaiLys/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DaiLyId,TenDaiLy")] DaiLy daiLy)
        {
            if (ModelState.IsValid)
            {
                db.Entry(daiLy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(daiLy);
        }

        // GET: Admin/DaiLys/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DaiLy daiLy = db.DaiLies.Find(id);
            if (daiLy == null)
            {
                return HttpNotFound();
            }
            return View(daiLy);
        }

        // POST: Admin/DaiLys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DaiLy daiLy = db.DaiLies.Find(id);
            db.DaiLies.Remove(daiLy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhanMemVeSo/PhanMemVeSo/Areas/Admin/Controllers/LoaiVeSoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.EFModels;

namespace PhanMemVeSo.Areas.Admin.Controllers
{
    public class LoaiVeSoesController : Controller
    {
        private PhanPhoiVeSoEntities db = new PhanPhoiVeSoEntities();

        // GET: Admin/LoaiVeSoes
        public ActionResult Index()
        {
            return View(db.LoaiVeSoes.ToList());
        }

        // GET: Admin/LoaiVeSoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiVeSo loaiVeSo = db.LoaiVeSoes.Find(id);
            if (loaiVeSo == null)
            {
                return HttpNotFound();
            }
            return View(loaiVeSo);
        }

        // GET: Admin/LoaiVeSoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiVeSoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LoaiVeSoId,TenTinh")] LoaiVeSo loaiVeSo)
        {
            if (ModelState.IsValid)
            {
                db.LoaiVeSoes.Add(loaiVeSo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(loaiVeSo);
        }

        // GET: Admin/LoaiVeSoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiVeSo loaiVeSo = db.LoaiVeSoes.Find(id);
            if (loaiVeSo == null)
            {
                return HttpNotFound();
            }
            return View(loaiVeSo);
        }

        // POST: Admin/LoaiVeSoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LoaiVeSoId,TenTinh")] LoaiVeSo loaiVeSo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loaiVeSo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loaiVeSo);
        }

        // GET: Admin/LoaiVeSoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiVeSo loaiVeSo = db.LoaiVeSoes.Find(id);
            if (loaiVeSo == null)
            {
                return HttpNotFound();
            }
            return View(loaiVeSo);
        }

        // POST: Admin/LoaiVeSoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LoaiVeSo loaiVeSo = db.LoaiVeSoes.Find(id);
            db.LoaiVeSoes.Remove(loaiVeSo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhanMemVeSo/PhanMemVeSo/Areas/Admin/Controllers/PhieuThusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.EFModels;

namespace PhanMemVeSo.Areas.Admin.Controllers
{
    public class PhieuThusController : Controller
    {
        private PhanPhoiVeSoEntities db = new PhanPhoiVeSoEntities();

        // GET: Admin/PhieuThus
        public ActionResult Index()
        {
            var phieuThus = db.PhieuThus.Include(p => p.DaiLy);
            return View(phieuThus.ToList());
        }

        // GET: Admin/PhieuThus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuThu phieuThu = db.PhieuThus.Find(id);
            if (phieuThu == null)
            {
                return HttpNotFound();
            }
            return View(phieuThu);
        }

        // GET: Admin/PhieuThus/Create
        public ActionResult Create()
        {
            ViewBag.DaiLyId = new SelectList(db.DaiLies, "DaiLyId", "TenDaiLy");
            ViewBag.DateNow = System.DateTime.Now.ToString("yyyy-MM-dd");
            return View();
        }

        // POST: Admin/PhieuThus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PhieuThuId,DaiLyId,NgayThu,TienThu")] PhieuThu phieuThu)
        {
            if (ModelState.IsValid)
            {
                db.PhieuThus.Add(phieuThu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DaiLyId = new SelectList(db.DaiLies, "DaiLyId", "TenDaiLy", phieuThu.DaiLyId);
            return View(phieuThu);
        }

        // GET: Admin/PhieuThus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuThu phieuThu = db.PhieuThus.Find(id);
            if (phieuThu == null)
            {
                return HttpNotFound();
            }
            ViewBag.DaiLyId = new SelectList(db.DaiLies, "DaiLyId", "TenDaiLy", phieuThu.DaiLyId);
            return View(phieuThu);
        }

        // POST: Admin/PhieuThus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PhieuThuId,DaiLyId,NgayThu,TienThu")] PhieuThu phieuThu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phieuThu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DaiLyId = new SelectList(db.DaiLies, "DaiLyId", "TenDaiLy", phieuThu.DaiLyId);
            return View(phieuThu);
        }

        // GET: Admin/PhieuThus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuThu phieuThu = db.PhieuThus.Find(id);
            if (phieuThu == null)
            {
                return HttpNotFound();
            }
            return View(phieuThu);
        }

        // POST: Admin/PhieuThus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhieuThu phieuThu = db.PhieuThus.Find(id);
            db.PhieuThus.Remove(phieuThu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhanMemVeSo/PhanMemVeSo/Areas/Admin/Controllers/QuanLyCongNoController.cs
using Model.Bus;
using Model.EFModels;
using Model.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhanMemVeSo.Areas.Admin.Controllers
{
    public class QuanLyCongNoController : Controller
    {
        private PhanPhoiVeSoEntities db = new PhanPhoiVeSoEntities();
        // GET: Admin/QuanLyCongNo
        public ActionResult Index(System.DateTime? ngayCanTim)
        {
            ViewBag.DateNow = System.DateTime.Now.ToString("yyyy-MM-dd");
            System.DateTime ngayCanTimGan = ngayCanTim.GetValueOrDefault(System.DateTime.Now);
            DaiLyBus daiLyBus = new DaiLyBus();
            List<PhieuCongNo> listPhieuCongNo = new List<PhieuCongNo>();
            foreach(var item in db.DaiLies)
            {
                PhieuCongNo phieuCongNo = new PhieuCongNo();
                phieuCongNo.DaiLyId = item.DaiLyId;
                phieuCongNo.TenDaiLy = item.TenDaiLy;
                phieuCongNo.TaiKhoan = daiLyBus.TinhToanCongNoTheoDaiLy(item.DaiLyId, ngayCanTimGan);
                listPhieuCongNo.Add(phieuCongNo);
            }
            return View(listPhieuCongNo);
        }
    }
}

PhanMemVeSo/PhanMemVeSo/Areas/Admin/Views/ADHome/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li class="active">Dashboard</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="content mt-3">
    <div class="col-sm-12">
        <div class="alert  alert-success alert-dismissible fade show" role="alert">
            Phần mềm<span class="badge badge-pill badge-success">Quản lý phát hành vé số</span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
    <a href="@Url.Action("Index","DaiLys")">

        <div class="col-sm-12 col-lg-6">
            <div class="card text-white bg-flat-color-1">
                <div class="card-body pb-0">
                    <i class="fa fa-handshake-o"></i>
                    Quản Lý Đại Lý
                </div>
            </div>
        </div>
    </a>
    <a href="@Url.Action("Index","LoaiVeSoes")">

        <div class="col-sm-12 col-lg-6">
            <div class="card text-white bg-flat-color-1">
                <div class="card-body pb-0">
                    <i class="fa fa-bars"></i>
                    Quản Lý Loại Vé Số
                </div>
            </div>
        </div>
    </a>

    <a href="@Url.Action("Index","PhieuDangKies")">

        <div class="col-sm-12 col-lg-6">
            <div class="card text-white bg-flat-color-1">
                <div class="card-body pb-0">
                    <i class="fa fa-id-card-o "></i>
                    Quản Lý Phiếu Đăng Ký
                </div>
            </div>
        </div>
    </a>

    <a href="@Url.Action("Index","DotPhatHanhs")">

        <div class="col-sm-12 col-lg-6">
            <div class="card text-white bg-flat-color-1">
                <div class="card-body pb-0">
                    <i class="fa fa-university "></i>
                    Quản Lý Đợt Phát Hành
                </div>
            </div>
        </div>
    </a>
    <a href="@Url.Action("Index","QuanLySoTrung")">

        <div class="col-sm-12 col-lg-6">
            <div class="card text-white bg-flat-color-1">
                <div class="card-body pb-0">
                    <i class="fa fa-ticket"></i>
                    Quản Lý Số Trúng
                </div>
            </div>
        </div>
    </a>
    <a href="@Url.Action("Index","PhieuThus")">

        <div class="col-sm-12 col-lg-6">
            <div class="card text-white bg-flat-color-1">
                <div class="card-body pb-0">
                    <i class="fa fa-file-text"></i>
                    Quản Lý phiếu thu
                </div>
            </div>
        </div>
    </a>
    <a href="@Url.Action("Index","QuanLyCongNo")">

        <div class="col-sm-12 col-lg-6">
            <div class="card text-white bg-flat-color-1">
                <div class="card-body pb-0">
                    <i class="fa fa-money"></i>
                    Quản Lý công nợ
                </div>
            </div>
        </div>
    </a>
</div> <!-- .content -->

@section Plugin1{
    <link rel="apple-touch-icon" href="~/Assets/admin/sufee-admin-dashboard-master/apple-icon.png">
    <link rel="shortcut icon" href="~/Assets/admin/sufee-admin-dashboard-master/favicon.ico">

    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/normalize.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/cs-skin-elastic.css">
    <!-- <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/scss/style.css">
    <link href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/lib/vector-map/jqvmap.min.css" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <!-- <script type="text/javascript" src="~/Assets/admin/sufee-admin-dashboard-master/https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
}

@section Plugin2{
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/plugins.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/main.js"></script>


    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/dashboard.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/lib/vector-map/jquery.vmap.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/lib/vector-map/jquery.vmap.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/lib/vector-map/jquery.vmap.sampledata.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/lib/vector-map/country/jquery.vmap.world.js"></script>
    <script>
        (function ($) {
            "use strict";

            jQuery('#vmap').vectorMap({
                map: 'world_en',
                backgroundColor: null,
                color: '#ffffff',
                hoverOpacity: 0.7,
                selectedColor: '#1de9b6',
                enableZoom: true,
                showTooltip: true,
                values: sample_data,
                scaleColors: ['#1de9b6', '#03a9f5'],
                normalizeFunction: 'polynomial'
            });
        })(jQuery);
    </script>
}