PhanMemVeSo/PhanMemVeSo/Areas/Admin/Controllers/DotPhatHanhsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.EFModels;
using Model.ViewModels;
using Model.Bus;
using System.Globalization;
using System.Net;
using System.Data.Entity;

namespace PhanMemVeSo.Areas.Admin.Controllers
{
    public class DotPhatHanhsController : Controller
    {
        private PhanPhoiVeSoEntities db = new PhanPhoiVeSoEntities();
        // GET: Admin/DotPhatHanhs
        public ActionResult Index(Nullable<DateTime> searchDate)
        {
            DateTime ngayPhatGanNhat = db.PhieuPhatHanhs.OrderByDescending(m => m.NgayPhat).Select(m => m.NgayPhat).FirstOrDefault();
            ViewBag.NgayPhatGanNhat = ngayPhatGanNhat;

            var listPhatHanh = db.PhieuPhatHanhs.ToList();
            
            String s = null;
            if (searchDate != null)
            {
                listPhatHanh=db.PhieuPhatHanhs.Where(m=>m.NgayPhat==searchDate).ToList();
                DateTime searchDate1 = searchDate ?? default(DateTime);
                DateTime d = searchDate1;
                s = d.ToString("yyyy-MM-dd");
            }
            else
            {
                s = ngayPhatGanNhat.ToString("yyyy-MM-dd");
            }
            
            ViewBag.SearchDate = s;
            return View(listPhatHanh);
        }

        // GET: Admin/PhieuPhatHanhs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuPhatHanh phieuPhatHanh = db.PhieuPhatHanhs.Find(id);
            if (phieuPhatHanh == null)
            {
                return HttpNotFound();
            }
            return View(phieuPhatHanh);
        }

        public ActionResult findDateandTypeVeSo()
        {
            ViewBag.LoaiVeSoId = new SelectList(db.LoaiVeSoes, "LoaiVeSoId", "TenTinh");
            ViewBag.DateNow = System.DateTime.Now.ToString("yyyy-MM-dd");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult findDateandTypeVeSo(int LoaiVeSoId,System.DateTime ngayPhatHanh)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Create",new { loaiVeSoId =LoaiVeSoId, ngayPhat =ngayPhatHanh});
            }



            return View();
        }

        // GET: Admin/PhieuPhatHanhs/Create
        public ActionResult Create(int loaiVeSoId ,System.DateTime ngayPhat)
        {

            ViewBag.LoaiVeSo = db.LoaiVeSoes.Where(m=>m.LoaiVeSoId==loaiVeSoId).Select(m=>m.TenTinh).SingleOrDefault();
            ViewBag.NgayPhatHanh = ngayPhat;

            DotPhatHanh dotPhatHanh = new DotPhatHanh();
            dotPhatHanh.NgayPhat = ngayPhat;
            dotPhatHanh.LoaiVeSoId = loaiVeSoId;
            List<PhieuPhatHanhVM> listPhieuPhatHanh = new List<PhieuPhatHanhVM>();
            var listDaiLyId = db.DaiLies.Select(m => m.DaiLyId).ToList();
            foreach(var item in listDaiLyId)
            {
                PhieuPhatHanhVM phieuPhatHanhVM = new PhieuPhatHanhVM();
                phieuPhatHanhVM.DaiLyId = item;
                DaiLyBus daiLyBus = new DaiLyBus();
                phieuPhatHanhVM.SLPhat=daiLyBus.TinhToanSLPhatTheoDaiLy(loaiVeSoId,item, ngayPhat   );
                phieuPhatHanhVM.TenDaiLy = db.DaiLies.Where(m => m.DaiLyId == item).Select(m => m.TenDaiLy).SingleOrDefault();
                listPhieuPhatHanh.Add(phieuPhatHanhVM);
            }
            dotPhatHanh.ListPhieuPhatHanh = listPhieuPhatHanh;
            
            return View(dotPhatHanh);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( DotPhatHanh dotPhatHanh,System.DateTime ngayPhat,int loaiVeSoId)
        {
            if (ModelState.IsValid)
            {
                foreach (var item in dotPhatHanh.ListPhieuPhatHanh)
                {
                    PhieuPhatHanh phieuPhatHanh = new PhieuPhatHanh();
                    phieuPhatHanh.LoaiVeSoId = loaiVeSoId;
                    phieuPhatHanh.NgayPhat = ngayPhat;
                    phieuPhatHanh.DaiLyId = db.DaiLies.Where(m=>m.TenDaiLy==item.TenDaiLy).Select(m=>m.DaiLyId).FirstOrDefault();
                    phieuPhatHanh.SLPhat = item.SLPhat;
                    db.PhieuPhatHanhs.Add(phieuPhatHanh);
                }
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(dotPhatHanh);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuPhatHanh phieuPhatHanh = db.PhieuPhatHanhs.Find(id);
            if (phieuPhatHanh == null)
            {
                return HttpNotFound();
            }
            ViewBag.DaiLyId = new SelectList(db.DaiLies, "DaiLyId", "TenDaiLy", phieuPhatHanh.DaiLyId);
            ViewBag.LoaiVeSoId = new SelectList(db.LoaiVeSoes, "LoaiVeSoId", "TenTinh", phieuPhatHanh.LoaiVeSoId);
            return View(phieuPhatHanh);
        }

        // POST: Admin/PhieuPhatHanhs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PhieuPhatHanhId,DaiLyId,LoaiVeSoId,NgayPhat,SLPhat,SLBanDuoc")] PhieuPhatHanh phieuPhatHanh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phieuPhatHanh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DaiLyId = new SelectList(db.DaiLies, "DaiLyId", "TenDaiLy", phieuPhatHanh.DaiLyId);
            ViewBag.LoaiVeSoId = new SelectList(db.LoaiVeSoes, "LoaiVeSoId", "TenTinh", phieuPhatHanh.LoaiVeSoId);
            return View(phieuPhatHanh);
        }
        // GET: Admin/PhieuPhatHanhs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuPhatHanh phieuPhatHanh = db.PhieuPhatHanhs.Find(id);
            if (phieuPhatHanh == null)
            {
                return HttpNotFound();
            }
            return View(phieuPhatHanh);
        }

        // POST: Admin/PhieuPhatHanhs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhieuPhatHanh phieuPhatHanh = db.PhieuPhatHanhs.Find(id);
            db.PhieuPhatHanhs.Remove(phieuPhatHanh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhanMemVeSo/PhanMemVeSo/Areas/Admin/Views/DotPhatHanhs/Create.cshtml
@model Model.ViewModels.DotPhatHanh
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create","DotPhatHanhs", new { ngayPhat=Model.NgayPhat,loaiVeSoId=Model.LoaiVeSoId },FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">


    <h4>Đợt phát hành ngày @ViewBag.NgayPhatHanh vé số @ViewBag.LoaiVeSo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @for (int i = 0; i < Model.ListPhieuPhatHanh.Count; i++)
    {

        <div class="form-group">
            Đại lý: @Html.EditorFor(modelItem => Model.ListPhieuPhatHanh[i].TenDaiLy, new { htmlAttributes = new {  @value = @Model.ListPhieuPhatHanh[i].TenDaiLy, @readonly = "readonly",@style= "background-color: #dee2e6;" } })
            
            <label class=" form-control-label">So luong phat:</label>
            @Html.EditorFor(modelItem => Model.ListPhieuPhatHanh[i].SLPhat, new { htmlAttributes = new {  @value = @Model.ListPhieuPhatHanh[i].SLPhat } })
        </div>
        <hr />
    }

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Plugin1{
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/normalize.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/cs-skin-elastic.css">
    <!-- <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/scss/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
}

@section Plugin2{
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/popper.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/plugins.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/main.js"></script>
}

PhanMemVeSo/PhanMemVeSo/Areas/Admin/Views/DotPhatHanhs/Delete.cshtml
@model Model.EFModels.PhieuPhatHanh

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LoaiVeSo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NgayPhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayPhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SLPhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SLPhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SLBanDuoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SLBanDuoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaiLy.TenDaiLy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaiLy.TenDaiLy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiVeSo.TenTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiVeSo.TenTinh)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

@section Plugin1{
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/normalize.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/cs-skin-elastic.css">
    <!-- <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/scss/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
}

@section Plugin2{
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/popper.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/plugins.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/main.js"></script>
}

PhanMemVeSo/PhanMemVeSo/Areas/Admin/Views/DotPhatHanhs/Details.cshtml
@model Model.EFModels.PhieuPhatHanh

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div>
    <h4>Thông tin phiếu phát hành</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NgayPhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayPhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SLPhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SLPhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SLBanDuoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SLBanDuoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaiLy.TenDaiLy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaiLy.TenDaiLy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiVeSo.TenTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiVeSo.TenTinh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PhieuPhatHanhId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section Plugin1{
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/normalize.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/cs-skin-elastic.css">
    <!-- <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/scss/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
}

@section Plugin2{
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/popper.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/plugins.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/main.js"></script>
}

PhanMemVeSo/PhanMemVeSo/Areas/Admin/Views/DotPhatHanhs/Edit.cshtml
@model Model.EFModels.PhieuPhatHanh

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li class="active">Dashboard</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-header">
                        <strong class="card-title">Credit Card</strong>
                    </div>
                    <div class="card-body">
                        <!-- Credit Card -->
                        <div id="pay-invoice">
                            <div class="card-body">
                                <div class="card-title">
                                    <h3 class="text-center">Sửa Phieu Phast Hanh</h3>
                                </div>
                                <hr>
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.PhieuPhatHanhId)
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.DaiLyId, "DaiLyId", htmlAttributes: new { @class = "control-label col-md-2" })
                                            @Html.DropDownList("DaiLyId", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.DaiLyId, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.LoaiVeSoId, "LoaiVeSoId", htmlAttributes: new { @class = "control-label col-md-2" })
                                        
                                            @Html.DropDownList("LoaiVeSoId", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.LoaiVeSoId, "", new { @class = "text-danger" })
                                        
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.NgayPhat, htmlAttributes: new { @class = "control-label col-md-2" })
                                        
                                            @Html.EditorFor(model => model.NgayPhat, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.NgayPhat, "", new { @class = "text-danger" })
                                        
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SLPhat, htmlAttributes: new { @class = "control-label col-md-2" })
                                        
                                            @Html.EditorFor(model => model.SLPhat, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.SLPhat, "", new { @class = "text-danger" })
                                        
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SLBanDuoc, htmlAttributes: new { @class = "control-label col-md-2" })
                                        
                                            @Html.EditorFor(model => model.SLBanDuoc, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.SLBanDuoc, "", new { @class = "text-danger" })
                                        
                                    </div>

                                    <div class="form-group">
                                        <input type="submit" value="Save" class="btn btn-default" />
                                    </div>
                                </div>
                                }
                            </div>
                        </div>
                    </div>

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


@section Plugin1{
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/normalize.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/cs-skin-elastic.css">
    <!-- <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/scss/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
}

@section Plugin2{
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/popper.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/plugins.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/main.js"></script>
}

PhanMemVeSo/PhanMemVeSo/Areas/Admin/Views/DotPhatHanhs/findDateandTypeVeSo.cshtml
@{
    ViewBag.Title = "findDateandTypeVeSo";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label mb-1">Chọn loại vé số</label>
        @Html.DropDownList("LoaiVeSoId", null, htmlAttributes: new {  })
    </div>

    <div class="form-group">
        <label class="control-label mb-1">Chọn Ngày Phát Hành</label>
        <input type="date" name="ngayPhatHanh" value="@ViewBag.DateNow" />
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btnbbbccc btn-default" />
    </div>
</div>
}

@section Plugin1{
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/normalize.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/cs-skin-elastic.css">
    <!-- <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="~/Assets/admin/sufee-admin-dashboard-master/assets/scss/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
}

@section Plugin2{
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/popper.min.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/plugins.js"></script>
    <script src="~/Assets/admin/sufee-admin-dashboard-master/assets/js/main.js"></script>
}